### ISSUE TITLE
init_lstm parameters reset for each batch

### ISSUE THREAD

**Issue by srikar2097** [chaoyuaw/pytorch-vcii#1]
@chaoyuaw Thank you for sharing the code. in [train.py line 124](https://github.com/chaoyuaw/pytorch-vcii/blob/master/train.py#L124), `init_lstm` is being "reset" for every batch. 

Is that by design? Please help me understand why resetting the interpolation-model encoder and decoder parameters `(encoder_h_1, encoder_h_2, encoder_h_3, decoder_h_1, decoder_h_2, decoder_h_3, decoder_h_4)` makes sense for each batch. wont the model learning be stunted?

**Comment by chaoyuaw** [comment]
@srikar2097 , thanks for the question!  These are hidden states, rather than parameters. At the beginning of each LSTM sequence, the hidden states are initialized to be zero.
