### ISSUE TITLE
Training testing split

### ISSUE THREAD

**Issue by XudongLinthu** [chaoyuaw/pytorch-vcii#9]
Hi, Chao Yuan,
Thanks a lot for your work!
I am trying to reproduce your result. I wonder if you can share your datasets split file for fair comparison?
Thanks a lot!
Xudong

**Comment by chaoyuaw** [comment]
Hi Xudong, Of course, the video ids could be found at
https://drive.google.com/drive/folders/1MOLuoGDE6lZnmXLJHTUNkJtfY1l2sZSC?usp=sharing

Thanks :)

**Comment by XudongLinthu** [comment]
Thanks!
